### ISSUE TITLE
Configuration.Default doesn’t exist

### ISSUE THREAD

**Issue by ReneD86** [timheuer/strava-net#2]
As described in the ReadMe.md, I’m trying to use the Configuration.Default property to add my api key and authenticate, however the Default property doesn’t seem to exist.

**Comment by sonuame** [comment]
Yes, it doesn't exists.
**UpdateParamsForAuth** function in ApiClient.cs doesn't look like doing anything.

**Comment by redowl3** [comment]
then any ideas how this should work?

**Comment by sonuame** [comment]
This is how I have made it work - Client Code

[Program.zip](https://github.com/timheuer/strava-net/files/3459656/Program.zip)

Updated 
D:\GitClones\StravaClient\Strava.Net\src\main\CsharpDotNet2\Strava\NET\Client\ApiClient.cs

**Comment by rowbot38** [comment]
I get:

Strava.NET.Client.ApiException: Error calling GetActivityById: {"message":"Resource Not Found","errors":[{"resource":"Activity","field":"","code":"not found"}]}
   at Strava.NET.Api.ActivitiesApi.GetActivityById(Nullable`1 id, Nullable`1 includeAllEfforts)
   at StravaClient.Program.Main(String[] args) in

Any ideas?

**Comment by sonuame** [comment]
This looks like the underlying API endpoint for strava doesnt exists or the Activity id doesn't exist.
Have you tried once with postman ?

**Comment by rowbot38** [comment]
Activity id exists. Has the endpoint changed?

**Comment by Spiggers** [comment]
I added the auth token to the header manually for each client instance

var client = new Strava.NET.Client.ApiClient();
client.AddDefaultHeader("Authorization", $"Bearer {AUTHCODE}");

**Comment by dimka11** [comment]
> This is how I have made it work - Client Code
> 
> [Program.zip](https://github.com/timheuer/strava-net/files/3459656/Program.zip)
> 
> Updated
> D:\GitClones\StravaClient\Strava.Net\src\main\CsharpDotNet2\Strava\NET\Client\ApiClient.cs

I have Strava.NET.Client.ApiException: Error calling GetActivityById: <div class='error4xx error-page' id='error404'>
<div class='container error-container'>
<div class='system-page error-body row'>
<div class='description col-md-6 col-md-offset-6'>
<h1>Sorry, this one stays red.</h1>
<p>The page you’re looking for doesn’t exist, but you’re not at a dead end. Here are a few options:</p>
<ul>
<li>Be sure you have the right url and try again</li>
<li>Sign up or log in at <a href='https://www.strava.com'>strava.com</a></li>
<li>See what the community’s been up to at <a href='https://blog.strava.com'>Strava Stories</a></li>
<li>Search for a particular <a href='https://www.strava.com/activities/search'>activity</a> or <a href='https://www.strava.com/clubs/search'>club</a></li>
<li>Get a little help from <a href='https://support.strava.com'>Strava Support</a></li>
</ul>
</div>
</div>
</div>
</div>

   at Strava.NET.Api.ActivitiesApi.GetActivityById(Nullable`1 id, Nullable`1 includeAllEfforts) in B:\Code\CSharp\StravaAPI\StravaAPI\Strava\NET\Api\ActivitiesApi.cs:line 228
   at StravaAPI.StravaApi.GetActivity(String ActivityName) in B:\Code\CSharp\StravaAPI\StravaAPI\StravaAPI.cs:line 83 
   with this it
